### ISSUE TITLE
How does I run ears with windows?

### ISSUE THREAD

**Issue by AndreasSchroeder** [jhasse/ears#10]
I want to run an ears-application on windows, but I can't compile. 

There is Always this error:

`error: linking with `link.exe` failed: exit code: 1181
  |
  = note: "C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\bin\\amd64\\link.exe" "/LIBPATH:C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\lib\\amd64" "/LIBPATH:C:\\Program Files (x86)\\Windows Kits\\10\\lib\\10.0.10240.0\\ucrt\\x64" "/LIBPATH:C:\\Program Files (x86)\\Windows Kits\\8.1\\lib\\winv6.3\\um\\x64" "/NOLOGO" "/NXCOMPAT" "/LIBPATH:C:\\Users\\Andi\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib" "C:\\Users\\Andi\\Desktop\\Git\\some_project\\target\\debug\\deps\\ears-f03cfcbcddf99b6f.0.o" "/OUT:C:\\Users\\Andi\\Desktop\\Git\\some_project\\target\\debug\\deps\\ears-f03cfcbcddf99b6f.dll" "/DEF:C:\\Users\\Andi\\AppData\\Local\\Temp\\rustc.EyrY6AH6bLTf\\lib.def" "C:\\Users\\Andi\\Desktop\\Git\\some_project\\target\\debug\\deps\\ears-f03cfcbcddf99b6f.metadata.o" "/OPT:REF,NOICF" "/DEBUG" "/LIBPATH:C:\\Users\\Andi\\Desktop\\Git\\some_project\\target\\debug\\deps" "/LIBPATH:C:\\Users\\Andi\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib" "openal.lib" "sndfile.lib" "C:\\Users\\Andi\\AppData\\Local\\Temp\\rustc.EyrY6AH6bLTf\\liblibc-83c2bd88b43ecde3.rlib" "C:\\Users\\Andi\\AppData\\Local\\Temp\\rustc.EyrY6AH6bLTf\\liblazy_static-13daae1d9a07c252.rlib" "/LIBPATH:C:\\Users\\Andi\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib" "std-259356a62c16e209.dll.lib" "C:\\Users\\Andi\\AppData\\Local\\Temp\\rustc.EyrY6AH6bLTf\\libcompiler_builtins-0c9c28ea236973f1.rlib" "advapi32.lib" "ws2_32.lib" "userenv.lib" "shell32.lib" "msvcrt.lib" "/DLL" "/IMPLIB:C:\\Users\\Andi\\Desktop\\Git\\some_project\\target\\debug\\deps\\ears-f03cfcbcddf99b6f.dll.lib"
  = note: Non-UTF-8 output: LINK : fatal error LNK1181: Eingabedatei \"openal.lib\" kann nicht ge\xf6ffnet werden.\r\n
`

I installedOpenAl and libsndfile for windows.
Moving the lib-files to the Visual-Studio-Folder gives a new error:

`error: process didn't exit successfully: `target\debug\chicken_fight_3000_ultimate_tournament.exe` (exit code: 3221225781)
C:/Users/Andi/.cargo/bin/cargo.exe: error while loading shared libraries: ?: cannot open shared object file: No such file or directory
`

**Comment by jhasse** [comment]
You'll have to use the GNU version of Rust. Type

```
rustup default stable-gnu
```

to switch to it. Then you'll have to either

1. let Rust use ld from MSYS2 to link (I don't know how to do that yet with rustup)
2. copy the missing .a files to a directory where the linker bundled with Rust can see them.

**Comment by AndreasSchroeder** [comment]
Ok, thanks, but where will I get the .a files from?

**Comment by jhasse** [comment]
Inside a [MSYS2](http://www.msys2.org/) shell type:

```sh
pacman -S mingw-w64-x86_64-libsndfile mingw-w64-x86_64-openal
```

**Comment by AndreasSchroeder** [comment]
Ok, now it is compiling, but ther are still this error :( :

`error: process didn't exit successfully: `target\debug\chicken_fight_3000_ultimate_tournament.exe` (exit code: 3221225781)
C:/Users/Andi/.cargo/bin/cargo.exe: error while loading shared libraries: ?: cannot open shared object file: No such file or directory
`

**Comment by jhasse** [comment]
That might be a missing DLL from `C:\msys64\mingw64\bin`. Try adding adding that path to your `PATH`, e. g. with

```
set PATH=%PATH%;C:\msys64\mingw64\bin
```

in cmd.exe. Inside the MSYS2-MinGW64 shell it should already be on the path.

**Comment by AndreasSchroeder** [comment]
hm still the same error

**Comment by jhasse** [comment]
Did you use the .a files from `C:\msys64\mingw64\lib` and copied them to Rust's lib dir? Can you check the output of `gcc --version`?

**Comment by AndreasSchroeder** [comment]
Ok, I copied the dll-files in the project-folder an it works now. Maybe the PATH-Variable is wrong. Thanks a lot for your help. :) 
👍

**Comment by jhasse** [comment]
You're welcome :)
