### ISSUE TITLE
Thread Safety

### ISSUE THREAD

**Issue by vimalloc** [jhasse/ears#6]
It looks like this doesn't (always) work in a multi threaded environment:

``` rust
extern crate ears;
use ears::{Sound, AudioController};
use std::thread;

fn main() {
    let mut handles = Vec::new();
    for _ in 0..10 {
        let handle = thread::spawn(move || {
            let mut snd = Sound::new("path_to_audio.wav").unwrap();
            snd.play();
            while snd.is_playing() {}
        });
        handles.push(handle);
    }

    for h in handles {
        match h.join() {
            Ok(_)  => println!("Thread exited successfully"),
            Err(_) => println!("Thread died"),
        };
    }
}
```

I'm guessing its something to do with the underlying openal stuff, so it probably isn't easy to fix and may be outside of the scope of this library. But, if it wasn't too bad to fix, it sure would be nice. If you had any ideas about where to start looking to track this down, maybe I could look at stuff and see what could be done to fix it.

**Comment by jhasse** [comment]
OpenAL is actually thread-safe. But one has to be careful when creating the context. I think the problem lies in this function: https://github.com/jhasse/ears/blob/master/src/internal.rs#L98

The following example works for me:

``` rust
extern crate ears;
use ears::{Sound, AudioController};
use std::thread;
use std::time::Duration;

fn main() {
    {
        Sound::new("res/shot.wav").unwrap();
        thread::sleep(Duration::from_millis(1000));
    }
    let mut handles = Vec::new();
    for _ in 0..10 {
        let handle = thread::spawn(move || {
            let mut snd = Sound::new("res/shot.wav").unwrap();
            snd.play();
            while snd.is_playing() {}
        });
        handles.push(handle);
    }

    for h in handles {
        match h.join() {
            Ok(_)  => println!("Thread exited successfully"),
            Err(_) => println!("Thread died"),
        };
    }
}
```

So I think it's the context creation which needs to be synchronized. I'll work on something :)

**Comment by jhasse** [comment]
Okay as far as I can tell, this could be fixed with a StaticMutex: https://doc.rust-lang.org/std/sync/struct.StaticMutex.html
But it's still unstable, so I would want to wait until it's merged into Rust stable.

Another fix would be to change the API: Let the user call an init() function.

**Comment by vimalloc** [comment]
That was fast :)

Personally, it isn't causing a big problem at all right now. A thread may panic here or there, but it just adds some extra printed lines and doesn't bring down the whole application or anything. It sounds like waiting for static mutex to stabilize is probably easier then changing the API, especially if calling init would be required (and cause breakage for everyone else using this).

Thanks!

**Comment by vimalloc** [comment]
Looks like this has been fixed with the ears::init() method (per https://github.com/jhasse/ears/blob/master/examples/many_sounds.rs)

Thanks!

**Comment by jhasse** [comment]
Actually calling ears::init() first is more of a workaround. As ears wants to be an *easy* API it should definitely not crash when doing something wrong.

**Comment by vimalloc** [comment]
Fair enough. In either case, thanks for providing the work around :)

**Comment by jhasse** [comment]
Using https://github.com/rust-lang-nursery/lazy-static.rs I managed to get this working :)

Can you check if it works for you? If it does, I'll release this as 0.4.0 :)

**Comment by vimalloc** [comment]
Yeah, for sure! Give me a bit and I'll try it later tonight.

Cheers!

**Comment by vimalloc** [comment]
That works perfectly for me. Thanks
